[[pages]]
path = "pages/search.py"
name = "Suchen & bearbeiten"
icon = "ğŸ”"

[[pages]]
path = "Pages/add.py"
name = "HinzufÃ¼gen"
icon = "â•"

[[pages]]
path = "Pages/delete.py"
name = "LÃ¶schen"
icon = "â¡"